const frisby = require('frisby');

describe('30 days of Postman - Day 20: Documentation', () => {    
    it('Get single Pokemon', async () => {
        let min = Math.ceil(1);
        let max = Math.floor(1011);
        let pokemonID = Math.floor(Math.random() * (max - min + 1)) + min
        const result = await frisby
            .get(`https://pokeapi.co/api/v2/pokemon/${pokemonID}`)
            .expect('status', 200)
        console.log(`Pokemon: ${result.json.forms[0].name}, id: ${pokemonID}`)
      });
})

// This request gets one random pokémon and displays its name and ID in the console.
// Link to the official documentation for pokeapi: https://pokeapi.co/docs/v2#pokemon
// The ID is a collection variable generated by the pre-request to get a random value 
// from 1 to 1010. Intended to determine a random pokémon ID.
